databases:
  - name: rails
    databaseName: rails_n21k
    user: matu47

services:
  - type: web
    name: Ulahua Cakes
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails_n21k
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false